---
language: python
python:
  - "3.10"
  - "3.11"
  - "3.12"
  - "3.13"
services:
  - docker
install:
  - pip install molecule docker
script:
  - molecule --version
  - ansible --version
  - molecule test
