---
# tasks file for hf_system_create_user_key

- name: Get existing users
  getent:
    database: passwd

- name: Create new user with OpenSSH keypair (4096 bits, RSA)
  user:
    name: "{{ new_user_name_linux }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
  with_items:
    - "{{ new_user_name_linux }}"
  when: item in getent_passwd.keys()

# TODO: write the key in .ssh