---
# tasks file for hf_nfs_server

# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: nfs_exports -> loop
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop: "{{ nfs_exports }}"

- name: Ensure directories to export exist
  file:  # noqa 208
    path: "{{ item.path }}"
    state: directory
    mode: '0777'
    owner: "nobody"
    group: "nogroup"
  with_items: "{{ nfs_exports }}"

- name: Copy exports file.
  template:
    src: exports.j2
    dest: /home/a/exports
    owner: root
    group: root
    mode: 0644
  notify: reload nfs

- name: Ensure nfs is running.
  service: "name={{ nfs_server_daemon }} state=started enabled=yes"
  when: nfs_exports|length
